[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 3


# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/TimilsinaBml05"
    weight = 1

[[social]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://instagram.com/__bimal_/"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/TimilsinaBimal/"
    weight = 3

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https:/linkedin.com/in/TimilsinaBimal/"
    weight = 3